/**
 * Images Defines
 * @author Passion UI <passionui.com>
 */

export const Images = {
  everLogo: require('@assets/images/ever-logo.png'),
  topSplash: require('@assets/images/topsplash.jpg'),
  kycCard2: require('@assets/images/IDcard.png'),
  idCard: require('@assets/images/id-card.png'),
  idCard1: require('@assets/images/id-card1.png'),
  avata2: require('@assets/images/avata-02.png'),
  calendarIcon: require('@assets/images/calendar.png'),
  homeicon2: require('@assets/images/homeicon2.png'),
  homeicon5: require('@assets/images/homeicon5.png'),
  homeicon6: require('@assets/images/homeicon6.png'),
  homeicon7: require('@assets/images/homeicon7.png'),
  homeicon8: require('@assets/images/homeicon8.png'),
  homepic1: require('@assets/images/homepic1.jpg'),
  homepic2: require('@assets/images/homepic2.jpg'),
  homepic3: require('@assets/images/homepic3.jpg'),
  homepic4: require('@assets/images/homepic4.jpg'),
  delivery1: require('@assets/images/delivery1.jpg'),
  delivery2: require('@assets/images/delivery2.png'),
  delivery3: require('@assets/images/delivery3.png'),
  delivery4: require('@assets/images/delivery4.png'),
  delivery5: require('@assets/images/delivery5.png'),
  delivery6: require('@assets/images/delivery6.png'),
  delivery7: require('@assets/images/delivery7.png'),
  call_step1: require('@assets/images/call-step1.png'),
  call_step2: require('@assets/images/call-step2.png'),
  call_step3: require('@assets/images/call-step3.png'),
  call_step4: require('@assets/images/call-step4.png'),
  call_step5: require('@assets/images/call-step5.png'),
  appointment_detail: require('@assets/images/appointment-detail.jpg'),
  google: require('@assets/images/google.png'),
  google_fit: require('@assets/images/google-fit.png'),
  freeChat: require('@assets/images/freeChat.jpg'),
  like: require('@assets/images/like.png'),
  everLogo: require('@assets/images/ic_logo.png'),
  qrcode: require('@assets/images/websiteQRCode_noFrame.png'),
  verifiedClinic: require('@assets/images/verified_clinic.png'),
  verifiedLocation: require('@assets/images/verified_location.png'),
  verifiedSupport: require('@assets/images/verified_support.png'),
  inviterefer: require('@assets/images/inviterefer.png'),
  spinner: require('@assets/images/spinner.gif'),
  gethelp: require('@assets/images/gethelp.png'),
  giveus: require('@assets/images/giveusfeedback.png'),
  call: require('@assets/images/call.png'),
  hide: require('@assets/images/hide.png'),
  show: require('@assets/images/show.png'),
  setting01: require('@assets/images/Profile/06-1-Profile.png'),
  setting02: require('@assets/images/setting02.png'),
  setting03: require('@assets/images/setting03.png'),
  setting04: require('@assets/images/setting04.png'),
  setting05: require('@assets/images/setting05.png'),
  setting06: require('@assets/images/Profile/06-3-Notification.png'),
  setting07: require('@assets/images/Profile/06-4-Accessibility.png'),
  setting08: require('@assets/images/Profile/06-5-Security.png'),
  setting09: require('@assets/images/Profile/06-6-Help.png'),
  setting10: require('@assets/images/Profile/06-7-Advice.png'),
  setting11: require('@assets/images/Profile/06-8-Policy.png'),
  setting12: require('@assets/images/Profile/06-9-Add_account.png'),
  setting13: require('@assets/images/Profile/06-10-SignOut.png'),
  setting14: require('@assets/images/Profile/06-11-Language.png'),
  CreditCardLogo: require('@assets/images/visa-mastercard.png'),
  CreditCardLogo2: require('@assets/images/CreditCardLogo.png'),
  CheckTrue: require('@assets/images/CheckTrue.png'),
  CheckFalse: require('@assets/images/CheckFalse.png'),
  Ayudhya: require('@assets/images/Ayudhya.png'),
  Bangkokbank: require('@assets/images/Bankokbank.png'),
  Krungthai: require('@assets/images/Krungthai.png'),
  Scb: require('@assets/images/Scb.png'),
  InternetBanking: require('@assets/images/Internet-banking.png'),
  Trash: require('@assets/images/trash.png'),
  PromptPay: require('@assets/images/PromptPay.png'),
  PromptPay2: require('@assets/images/PromptPay2.png'),
  tempDrug: require('@assets/images/ever-infrastructure.png'),
  Dental: require('@assets/images/Dental.png'),
  NCD: require('@assets/images/NCD.png'),
  Orthopedic: require('@assets/images/Orthopedic.png'),
  Pediatric: require('@assets/images/Pediatric.png'),
  Psychologist: require('@assets/images/Psychologist.png'),
  Reproductive: require('@assets/images/Reproductive.png'),
  sendIcon: require('@assets/images/sendIcon.png'),
  networkerror: require('@assets/images/icon_wrong.png'),
  defaultUser: require('@assets/images/user.png'),
  labResult: require('@assets/images/labResult.png'),
  hospital: require('@assets/images/hospital.png'),
  drugList: require('@assets/images/drugList.png'),
  Clinic: require('@assets/images/clinic.png'),
  ClinicTopIcon: require('@assets/images/clinic_top_icon.png'),

  Rheumatology: require('@assets/logo/Rheumatology.png'),
  Cardiology: require('@assets/logo/Cardiology.png'),
  Dermatology: require('@assets/logo/Dermatology.png'),
  Endocrinology: require('@assets/logo/Endocrinology.png'),
  GeneralMedicine: require('@assets/logo/GeneralMedicine.png'),
  Pediatrics: require('@assets/logo/Pediatric.png'),
  Pulmonology: require('@assets/logo/Pulmonology.png'),
  Nephrology: require('@assets/logo/Nephrology.png'),
  Neurology: require('@assets/logo/Neurology.png'),
  NeuroSurgery: require('@assets/logo/NeuroSurgeryx.png'),
  Ophthalmology: require('@assets/logo/Opthalmology.png'),
  Psychology: require('@assets/logo/Psychology.png'),
  Orthopedics: require('@assets/logo/Orthopedics.png'),
  Urinology: require('@assets/logo/Urinology.png'),

  MorningLogo: require('@assets/logotime/morning.png'),
  AfternoonLogo: require('@assets/logotime/afternoon.png'),
  EveningLogo: require('@assets/logotime/evening.png'),

  WalkSteps: require('@assets/telemonitoring/walkSteps.png'),
  BloodPressure: require('@assets/telemonitoring/bloodPressure.png'),
  BloodGlucose: require('@assets/telemonitoring/bloodGlucose.png'),
  Weight: require('@assets/telemonitoring/weight.png'),
  O2Sat: require('@assets/telemonitoring/o2Sat.png'),
  BodyTemp: require('@assets/telemonitoring/bodyTemp.png'),
  HeartRate: require('@assets/telemonitoring/heartRate.png'),
  Morning: require('@assets/telemonitoring/morning.png'),
  Noon: require('@assets/telemonitoring/noon.png'),
  Evening: require('@assets/telemonitoring/evening.png'),
  Bed: require('@assets/telemonitoring/bed.png'),

  PharmacyImage: require('@assets/images/Pharmacy.png'),

  DoctorPlaceholder: require('@assets/timeline/doctor-placeholder.png'),
  DoctorIcon: require('@assets/timeline/doctorIcon.png'),
  DoctorPending: require('@assets/timeline/timeline-doctor-pending.png'),
  DoctorPendingInactive: require('@assets/timeline/timeline-doctor-pending-inactive.png'),
  DoctorCompleted: require('@assets/timeline/timeline-doctor-completed.png'),
  DoctorCompletedInactive: require('@assets/timeline/timeline-doctor-completed-inactive.png'),
  PharmacistPending: require('@assets/timeline/timeline-pharmacist-pending.png'),
  PharmacistPendingInactive: require('@assets/timeline/timeline-pharmacist-pending-inactive.png'),
  PharmacistCompleted: require('@assets/timeline/timeline-pharmacist-completed.png'),
  PharmacistCompletedInactive: require('@assets/timeline/timeline-pharmacist-completed-inactive.png'),

  HomeInactiveIcon: require('@assets/icons/home-inactive.png'),
  HomeActiveIcon: require('@assets/icons/home-active.png'),
  BookingInactiveIcon: require('@assets/icons/booking-inactive.png'),
  BookingActiveIcon: require('@assets/icons/booking-active.png'),
  HealthInactiveIcon: require('@assets/icons/health-inactive.png'),
  HealthActiveIcon: require('@assets/icons/health-active.png'),
  AccountInactiveIcon: require('@assets/icons/account-inactive.png'),
  AccountActiveIcon: require('@assets/icons/account-active.png'),

  ios_ever: require('@assets/ios-setting/ios_ever.png'),
  ios_health: require('@assets/ios-setting/ios_health.png'),
  ios_privacy: require('@assets/ios-setting/ios_privacy.png'),
  ios_settings: require('@assets/ios-setting/ios_settings.png'),

  thailand: require('@assets/images/language/thailand.png'),
  united_kingdom: require('@assets/images/language/united-kingdom.png'),

  facebook_signIn: require('@assets/icons/facebook_login.png'),
  google_signIn: require('@assets/icons/google_login.png'),
  line_signIn: require('@assets/icons/line_login.png'),
};
