import { Platform, StyleSheet } from 'react-native';

export default theme =>
  StyleSheet.create({
    sectionContainer: {
      backgroundColor: 'white',
      marginHorizontal: 10,
      marginTop: 10,
      borderRadius: 10,
      shadowColor: Platform.OS === 'android' ? '#000' : '#B2ADAD',
      shadowOffset: { width: 1, height: 3 },
      shadowOpacity: 0.5,
      shadowRadius: 4,
      elevation: 6,
      padding: 10,
    },
    ViewRow: {
      marginBottom: 10,
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    titleText: {
      lineHeight: 25,
      fontSize: theme.fontSizeSmall,
      fontFamily: theme.fontFamilyBold,
    },
    sectionOrder: {
      borderColor: '#eeeeee',
      borderWidth: 1,
      borderRadius: 8,
    },
    OrderList: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 10,
    },
    Quantity: {
      backgroundColor: '#00BAE510',
      height: 20,
      width: 20,
      alignItems: 'center',
      borderRadius: 5,
      marginVertical: 10,
      marginLeft: 10,
    },
    QuantityText: {
      fontSize: theme.fontSizeSmallest,
      fontFamily: theme.fontFamilyDefault,
      color: theme.colors.primary,
    },
    listName: {
      // marginHorizontal: 35,
      marginVertical: 7,
      marginLeft: 15,
    },
    listText: {
      fontSize: theme.fontSizeSmall,
      fontFamily: theme.fontFamilyBold,
    },
    priceList: {
      position: 'absolute',
      right: 20,
      top: 10,
    },
    priceText: {
      fontSize: theme.fontSizeSmall,
      fontFamily: theme.fontFamilyDefault,
      marginVertical: 10,
    },
    threeColRow: {
      justifyContent: 'space-between',
      flexDirection: 'row',
      alignItems: 'center',
    },
    priceWrapper: {
      marginRight: 20,
      marginLeft: 35,
    },
    drugName: {
      fontSize: theme.fontSizeSmall,
      fontFamily: theme.fontFamilyDefault,
      padding: 10,
    },
    drugPrice: {
      fontSize: theme.fontSizeSmaller,
      fontFamily: theme.fontFamilyDefault,
      color: theme.colors.secondary,
      padding: 10,
    },
    prescriptionSection: {
      borderWidth: 1,
      borderColor: theme.colors.grey5,
      borderRadius: 10,
      padding: 10,
      marginTop: 10,
    },
    rowSection: { flexDirection: 'row' },
    divider: {
      borderColor: '#eeeeee',
      borderWidth: 0.8,
      marginTop: 20,
    },
    ViewSections: {
      marginTop: 10,
      padding: 10,
      backgroundColor: theme.colors.white,
    },
    titleTextSuggest: {
      lineHeight: 25,
      fontSize: theme.fontSizeSmall,
      fontFamily: theme.fontFamilyBold,
      color: '#A9A9A9',
      marginBottom: 0,
      marginVertical: 15,
      marginHorizontal: 10,
      position: 'absolute',
      bottom: 120,
      left: 10,
    },
    DrugListCarousel: {
      backgroundColor: 'white',
      marginHorizontal: 5,
      marginRight: 5,
      borderRadius: 10,
      flexDirection: 'row',
      shadowColor: Platform.OS === 'android' ? '#00000070' : '#B2ADAD',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.2,
      shadowRadius: 10,
      elevation: 5,
      padding: 7,
      alignItems: 'center',
    },
    suggestionCard: {
      flexDirection: 'row',
      padding: 0,
      paddingBottom: 10,
      paddingVertical: 40,
    },
    suggestionPriceText: {
      fontSize: theme.fontSizeSmallest,
      fontFamily: theme.fontFamilyDefault,
      color: theme.colors.secondary,
    },
    helperText: {
      fontSize: theme.fontSizeSmallest,
      fontFamily: theme.fontFamilyDefault,
      color: theme.colors.grey3,
    },
    drugEvent: {
      fontFamily: theme.fontFamilyDefault,
      fontSize: theme.fontSizeSmallest,
      color: theme.colors.grey3,
      paddingHorizontal: 10,
      marginTop: -10,
    },
  });
