export const LOGIN_REQUEST = 'app/Auth/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'app/Auth/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'app/Auth/LOGIN_FAILURE';

export const REGISTER_REQUEST = 'app/Auth/REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'app/Auth/REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'app/Auth/REGISTER_FAILURE';

export const LOGOUT_REQUEST = 'app/Auth/LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'app/Auth/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'app/Auth/LOGOUT_FAILURE';

export const LOGOUT_TELE_REQUEST = 'app/Auth/LOGOUT_TELE_REQUEST';
export const LOGOUT_TELE_SUCCESS = 'app/Auth/LOGOUT_TELE_SUCCESS';

export const IS_AUTH_REQUEST = 'app/Auth/IS_AUTH_REQUEST';
export const IS_AUTH_SUCCESS = 'app/Auth/IS_AUTH_SUCCESS';

export const LOGIN_THIRD_PARTY_REQUEST = 'app/Auth/LOGIN_THIRD_PARTY_REQUEST';
export const LOGIN_THIRD_PARTY_SUCCESS = 'app/Auth/LOGIN_THIRD_PARTY_SUCCESS';
export const LOGIN_THIRD_PARTY_FAILURE = 'app/Auth/LOGIN_THIRD_PARTY_FAILURE';

export const RESET_REGISTER_DATA = 'app/Auth/RESET_REGISTER_DATA';

export const SEND_INFO_FORM = 'app/Auth/SEND_INFO_FORM';
export const CLEAR_INFO_FORM = 'app/Auth/CLEAR_INFO_FORM';

export const UPDATE_USER_INFO_THIRD_PARTY_REQUEST =
  'app/Auth/UPDATE_USER_INFO_THIRD_PARTY_REQUEST';
export const UPDATE_USER_INFO_THIRD_PARTY_SUCCESS =
  'app/Auth/UPDATE_USER_INFO_THIRD_PARTY_SUCCESS';
export const UPDATE_USER_INFO_THIRD_PARTY_FAILURE =
  'app/Auth/UPDATE_USER_INFO_THIRD_PARTY_FAILURE';
