export const GET_CONTENT_FEED_REQUEST =
  'app/ContentFeed/GET_CONTENT_FEED_REQUEST';
export const GET_CONTENT_FEED_FAILURE =
  'app/ContentFeed/GET_CONTENT_FEED_FAILURE';
export const GET_CONTENT_FEED_SUCCESS =
  'app/ContentFeed/GET_CONTENT_FEED_SUCCESS';

export const GET_CONTENT_FEED_CATEGORIES_REQUEST =
  'app/ContentFeed/GET_CONTENT_FEED_CATEGORIES_REQUEST';
export const GET_CONTENT_FEED_CATEGORIES_FAILURE =
  'app/ContentFeed/GET_CONTENT_FEED_CATEGORIES_FAILURE';
export const GET_CONTENT_FEED_CATEGORIES_SUCCESS =
  'app/ContentFeed/GET_CONTENT_FEED_CATEGORIES_SUCCESS';

export const CLEAR_REQUEST = 'app/ContentFeed/CLEAR_REQUEST';
export const CLEAR_SUCCESS = 'app/ContentFeed/CLEAR_SUCCESS';
