export const GET_HIE_HISTORY_APPOINTMENT_REQUEST =
  'app/HieAppointment/GET_HIE_HISTORY_APPOINTMENT_REQUEST';
export const GET_HIE_HISTORY_APPOINTMENT_SUCCESS =
  'app/HieAppointment/GET_HIE_HISTORY_APPOINTMENT_SUCCESS';
export const GET_HIE_HISTORY_APPOINTMENT_FAILURE =
  'app/HieAppointment/GET_HIE_HISTORY_APPOINTMENT_FAILURE';

export const GET_HIE_APPOINTMENT_REQUEST =
  'app/HieAppointment/GET_HIE_APPOINTMENT_REQUEST';
export const GET_HIE_APPOINTMENT_SUCCESS =
  'app/HieAppointment/GET_HIE_APPOINTMENT_SUCCESS';
export const GET_HIE_APPOINTMENT_FAILURE =
  'app/HieAppointment/GET_HIE_APPOINTMENT_FAILURE';

export const CLEAR_REQUEST = 'app/HieAppointment/CLEAR_REQUEST';
export const CLEAR_SUCCESS = 'app/HieAppointment/CLEAR_SUCCESS';
