export const GET_SAVELIST_REQUEST = 'app/Savelist/GET_SAVELIST_REQUEST';
export const GET_SAVELIST_SUCCESS = 'app/Savelist/GET_SAVELIST_SUCCESS';
export const GET_SAVELIST_FAILURE = 'app/Savelist/GET_SAVELIST_FAILURE';

export const CREATE_SAVELIST_REQUEST = 'app/Savelist/CREATE_SAVELIST_REQUEST';
export const CREATE_SAVELIST_SUCCESS = 'app/Savelist/CREATE_SAVELIST_SUCCESS';
export const CREATE_SAVELIST_FAILURE = 'app/Savelist/CREATE_SAVELIST_FAILURE';

export const ADD_ITEM_SAVELIST_REQUEST =
  'app/Savelist/ADD_ITEM_SAVELIST_REQUEST';
export const ADD_ITEM_SAVELIST_SUCCESS =
  'app/Savelist/ADD_ITEM_SAVELIST_SUCCESS';
export const ADD_ITEM_SAVELIST_FAILURE =
  'app/Savelist/ADD_ITEM_SAVELIST_FAILURE';

export const DELETE_ITEM_SAVELIST_REQUEST =
  'app/Savelist/DELETE_ITEM_SAVELIST_REQUEST';
export const DELETE_ITEM_SAVELIST_SUCCESS =
  'app/Savelist/DELETE_ITEM_SAVELIST_SUCCESS';
export const DELETE_ITEM_SAVELIST_FAILURE =
  'app/Savelist/DELETE_ITEM_SAVELIST_FAILURE';

export const CLEAR_REQUEST = 'app/Savelist/CLEAR_REQUEST';
export const CLEAR_SUCCESS = 'app/Savelist/CLEAR_SUCCESS';
