export const SET_TELEMEDICINE = 'app/Telemedicine/SET_TELEMEDICINE';
export const GET_TELEMEDICINE_REQUEST =
  'app/Telemedicine/GET_TELEMEDICINE_REQUEST';
export const GET_TELEMEDICINE_SUCCESS =
  'app/Telemedicine/GET_TELEMEDICINE_SUCCESS';
export const GET_TELEMEDICINE_FAILURE =
  'app/Telemedicine/GET_TELEMEDICINE_FAILURE';

export const SAVE_TELEMEDICINE_REQUEST =
  'app/Telemedicine/SAVE_TELEMEDICINE_REQUEST';
export const SAVE_TELEMEDICINE_SUCCESS =
  'app/Telemedicine/SAVE_TELEMEDICINE_SUCCESS';
export const SAVE_TELEMEDICINE_FAILURE =
  'app/Telemedicine/SAVE_TELEMEDICINE_FAILURE';

export const CLEAR_TELEMEDICINE_REQUEST =
  'app/Telemedicine/CLEAR_TELEMEDICINE_REQUEST';
export const CLEAR_TELEMEDICINE_SUCCESS =
  'app/Telemedicine/CLEAR_TELEMEDICINE_SUCCESS';
