export const GET_USER_REQUEST = 'app/User/GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'app/User/GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'app/User/GET_USER_FAILURE';
export const GET_UPDATE_INFO_REQUEST = 'app/User/GET_UPDATE_INFO_REQUEST';
export const GET_UPDATE_ADDRESS_INFO_REQUEST =
  'app/User/GET_UPDATE_ADDRESS_INFO_REQUEST';
export const GET_UPDATE_ADDRESS_INFO_SUCCESS =
  'app/User/GET_UPDATE_ADDRESS_INFO_SUCCESS';
export const CLEAR_REQUEST = 'app/User/CLEAR_REQUEST';
export const CLEAR_SUCCESS = 'app/User/CLEAR_SUCCESS';

export const UPDATE_USER_ORG_REQUEST = 'app/User/UPDATE_USER_ORG_REQUEST';
export const UPDATE_USER_ORG_SUCCESS = 'app/User/UPDATE_USER_ORG_SUCCESS';
export const UPDATE_USER_ORG_FAILURE = 'app/User/UPDATE_USER_ORG_FAILURE';

export const GET_USER_SETTING_REQUEST = 'app/User/GET_USER_SETTING_REQUEST';
export const UPDATE_USER_SETTING_LOCAL = 'app/User/UPDATE_USER_SETTING_LOCAL';
export const UPDATE_USER_SETTING_REQUEST =
  'app/User/UPDATE_USER_SETTING_REQUEST';
export const UPDATE_USER_SETTING_SUCCESS =
  'app/User/UPDATE_USER_SETTING_SUCCESS';
export const UPDATE_USER_SETTING_FAILURE =
  'app/User/UPDATE_USER_SETTING_FAILURE';

export const CHANGE_VERIFY_STATUS = 'app/User/CHANGE_VERIFY_STATUS';

export const GET_USER_THIRD_PARTY_SUCCESS =
  'app/User/GET_USER_THIRD_PARTY_SUCCESS';

export const UPDATE_VERIFY_USER = 'app/User/UPDATE_VERIFY_USER';
