
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'PlanRn' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  # use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
#  pod 'react-native-fitness', :path => '../node_modules/@ovalmoney/react-native-fitness'
#   use_flipper!()


  # pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'

#  post_install do |installer|
#    installer.pods_project.build_configurations.each do |config|
#      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#    end
#    flipper_post_install(installer)
#    installer.pods_project.targets.each do |target|
#      target.build_configurations.each do |config|
#        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
#      end
#    end
#  end

post_install do |installer|
   react_native_post_install(installer)

   # Apple Silicon builds require a library path tweak for Swift library discovery or "symbol not found" for swift things
   installer.aggregate_targets.each do |aggregate_target|
     aggregate_target.user_project.native_targets.each do |target|
       target.build_configurations.each do |config|
         config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)']
       end
     end
     aggregate_target.user_project.save
   end

    # Flipper requires a crude patch to bump up iOS deployment target, or "error: thread-local storage is not supported for the current target"
   # I'm not aware of any other way to fix this one other than bumping iOS deployment target to match react-native (iOS 11 now)
   installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
   end

   # ...but if you bump iOS deployment target, Flipper barfs again "Time.h:52:17: error: typedef redefinition with different types"
   # We need to make one crude patch to RCT-Folly - set `__IPHONE_10_0` to our iOS target + 1
   # https://github.com/facebook/flipper/issues/834 - 84 comments and still going...
   `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_12_0/' Pods/RCT-Folly/folly/portability/Time.h`
 end

use_flipper!({ 'Flipper'=> '0.138.0' })

use_react_native!(
  :path => config[:reactNativePath],
  :hermes_enabled => true
)

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'react-native-fitness', :path => '../node_modules/@ovalmoney/react-native-fitness'
  pod 'Firebase/Analytics'

  permissions_path = '../node_modules/react-native-permissions/ios'

   pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
   pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
   pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID.podspec"
   pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
   pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
   pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
   pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
   pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
   pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders.podspec"
   pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition.podspec"

end